/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_application_handle_WindowHandler */

#ifndef _Included_com_application_handle_WindowHandler
#define _Included_com_application_handle_WindowHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_application_handle_WindowHandler
 * Method:    getHwnd
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_application_handle_WindowHandler_getHwnd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
